### ISSUE TITLE
Separate icons for different types of vegetation

### ISSUE THREAD

**Issue by smbantjes** [Ghini/ghini.web#18]
Is it possible to have different icons for different types of vegetation like trees, palms, bushes, herbs, grasses, orchids.....

**Comment by mfrasca** [comment]
yes it is possible. in the ghini.desktop database the `species` table contains a `habit` field. not always filled in, but it is there and could be exported into the ghini.web database.
it's not too difficult to add a custom icon to the standard list. technically, you either follow the directions for custom icons, or you add them to the file `glyphicons-halflings.png` and refer them from `bootstrap.css`.
already did it once, for `icon-faucet`.

**Comment by mfrasca** [comment]
@smbantjes , do you want to look for possible glyphs? they should fit in 24×24 and actually the limit is tighter. have a look at the [glyphicons-halflings](https://github.com/Ghini/ghini.web/blob/master/public/img/glyphicons-halflings.png) file. the leaf is sixth row, third column.

**Comment by mfrasca** [comment]
more recent versions of bootstrap include a couple more icons for plants. I am going to move to that. we will loose 'icon-faucet' for the time being, and if we need it (to indicate water points), we can still revive it.

**Comment by mfrasca** [comment]
there is a nice collection of icons in the GPL software for Telegram. they are coloured, not black and white. we could use them... (resized to 20×20, they are now 24×24)
![plant-icons](https://cloud.githubusercontent.com/assets/122869/21454440/8ccfab06-c8e6-11e6-9ef3-68421aee6c1a.png)

but to use them as they are, I think we need change the marker background, I think we should prepare some white space in a coloured marker frame. something like ...
![icon-blue](https://cloud.githubusercontent.com/assets/122869/21454416/51f1c488-c8e6-11e6-88c2-b84238289baf.png)

**Comment by mfrasca** [comment]
some possible resulting icons, based on the blue background:
grass: ![icon-grass](https://cloud.githubusercontent.com/assets/122869/21454654/292caffc-c8e8-11e6-8989-ca2aa126f3a6.png)
banana: ![icon-banana](https://cloud.githubusercontent.com/assets/122869/21454649/278c56c0-c8e8-11e6-8b88-5b8f8af58c66.png)
generic tree: ![icon-tree](https://cloud.githubusercontent.com/assets/122869/21454650/27dcf454-c8e8-11e6-82dd-4608404a7bf4.png)
cactus: ![icon-cactus](https://cloud.githubusercontent.com/assets/122869/21454651/28329dfa-c8e8-11e6-8db6-03244367d7ee.png)
conifer: ![icon-conifer](https://cloud.githubusercontent.com/assets/122869/21454652/288926c0-c8e8-11e6-91f1-7f1edc80969b.png)
palm: ![icon-palm](https://cloud.githubusercontent.com/assets/122869/21454653/28ddcd1a-c8e8-11e6-9253-84597fdd4310.png)

**Comment by mfrasca** [comment]
this works, it's not based on the habit, it's based on the `Ordo` to which the species belongs. we should import the ordo-familia-tribus-genus database, but that's a different issue.
