### ISSUE TITLE
Exporting gardens collections as OpenData

### ISSUE THREAD

**Issue by hyances** [Ghini/ghini.web#31]
One additional service could be liberate gardens data for public, so scientist, data analyzers or communities around the globe can use this data for any purpose.  The export process could include license and file format selection by the author or institution, then the extract appear as a register in a table with: name, date, user, license and file format to download.

**Global garden data**.  This page could suggest to carry this data to OpenStreetMap, as a way to aggregate this data in a global geographic way or a global instance of ghini.web can work this manner too.

**Comment by mfrasca** [comment]
Hola Humberto! speaking of data sharing, have a look at the BGCI export (report) in ghini.desktop. the BGCI shares back the contributed data to the botanic worldwide community.
About exporting geographic plant data to OSM, I'm not so sure. it would, I think, very much clutter the OSM database, except, maybe, for major trees, and even then, I have doubts. have you seen how many trees in the Medellín garden? and these are only their trees.
I have not personally surveyed the Medellín garden, so all trees are at the same level, in the Cuchubo garden, which I have helped surveying, ghini.web shows plants according to the zoom level. I would select some of the trees for exporting them to OSM, but I would not do this from ghini.web.
ghini.web is more for passive fruition of the data.
it's ghini.desktop the central data management station.

**Comment by mfrasca** [comment]
as said: »ghini.web is more for passive fruition of the data.«
please do reopen if you have more specific and concrete info.
